name: koreader-highlight-joplin-server

on:
  push:
    paths:
    - 'koreader-highlight-joplin-server/Dockerfile'
    - 'koreader-highlight-joplin-server/root/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "JOPLIN_VER=$(echo `grep -n "JOPLIN_VER=" koreader-highlight-joplin-server/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./koreader-highlight-joplin-server
          file: ./koreader-highlight-joplin-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            johngong/koreader-highlight-joplin-server:latest
            johngong/koreader-highlight-joplin-server:${{ env.JOPLIN_VER }}
            ghcr.io/gshang2017/koreader-highlight-joplin-server:latest
            ghcr.io/gshang2017/koreader-highlight-joplin-server:${{ env.JOPLIN_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/koreader-highlight-joplin-server
          short-description: koreader-highlight-joplin-server:${{ env.JOPLIN_VER }},koreader标注导出joplin服务器。
          readme-filepath: ./koreader-highlight-joplin-server/README.md
